### ISSUE TITLE
Unable to extract the data from the website

### ISSUE THREAD

**Issue by abaheti95** [mandarjoshi90/triviaqa#2]
Hi,
I was trying to download the [unfiltered-questions](http://nlp.cs.washington.edu/triviaqa/data/triviaqa-rc.tar.gz) on the website.
I ran the command
`wget http://nlp.cs.washington.edu/triviaqa/data/triviaqa-rc.tar.gz`
Now when I tried to extract it using the command 
`tar xvzf triviaqa-unfiltered.tar.gz`
It gave me the following error:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Even extraction with `gunzip` failed similarly. Could you mention what is the compression type or the correct file type of this file?

**Comment by eunsol** [comment]
Hi Ashutosh!

The file is actually in the tar format.
Please just rename it from `.tar.gz` to `.tar`, and it should work.
We will fix it online soon!

best,
Eunsol

**Comment by mandarjoshi90** [comment]
Thanks Ashutosh. Changed the format to tar.gz.
