### ISSUE TITLE
how to convert TriviaQA to squad format?

### ISSUE THREAD

**Issue by houzhenzhen** [mandarjoshi90/triviaqa#3]
HI!  i want to convert dataset to squad formation ,but I don't  clear which file need to use, i try as bellow, but meet some error.
####
root@843d9505135f:/home/trivia/utils# python convert_to_squad_format.py --triviaqa_file dataset/wikipedia-dev.json --squad_file squad --wikipedia_dir dataset/wikipdia-dev.json  --web_dir dataset/web-dev.json
  0%|                                                                                                                        | 0/14229 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "convert_to_squad_format.py", line 110, in <module>
    convert_to_squad_format(args.triviaqa_file, args.squad_file)
  File "convert_to_squad_format.py", line 67, in convert_to_squad_format
    text = get_text(qad, qad['Source'])
  File "convert_to_squad_format.py", line 12, in get_text
    return utils.get_file_contents(local_file, encoding='utf-8')
  File "/home/trivia/utils/utils.py", line 10, in get_file_contents
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/wikipdia-dev.json/White.txt'
####
 icould you tell me more detail how to convert？

**Comment by houzhenzhen** [comment]
@mandarjoshi90  when i run , many file can't found,  I want to know if you have file TriviaQA convert to squada  form.thanks

**Comment by houzhenzhen** [comment]
Thanks for your quick answer, it work!

**Comment by boukhasmarsoufian** [comment]
@mandarjoshi90 can i have help to convert wikiQA data to squad format, thank you.
