### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by m-r-g** [mandarjoshi90/triviaqa#4]
Can you please add an open source license (preferably Apache 2.0)? This is mainly important for the evaluation script.

**Comment by Phirefly9** [comment]
I am also looking for a license for the utils folder

**Comment by mandarjoshi90** [comment]
Apologies for missing this, earlier. I added the Apache 2.0 license. 

Best,
Mandar

**Comment by TomerRonen34** [comment]
Hello, does the Apache 2.0 license also apply to the data? If not, what is the dataset's license? Thanks
